context:
  name: jupyterlab-dyno
  version: 0.0.0.dev0
  account: EconForge

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{account}}/${{name}}/archive/refs/tags/v${{version}}.tar.gz

build:
  number: 1
  noarch: python
  script: pip install . --no-deps -vv --no-build-isolation --ignore-installed --no-index

requirements:
  host:
    - python >=3.9,<3.14
    - hatchling>=1.5.0
    - pip >=25.1.1,<26
    - nodejs >=24.4.0,<24.5
    - hatch-nodejs-version>=0.3.2
    - hatch-jupyter-builder >=0.5.0
    - jupyterlab >=4.0.0,<5
  run:
    - dyno >=0.1.5.dev5
    - xeus-python >=0.17.4,<0.18
    - nlohmann_json ==3.11.3
about:
  homepage: https://github.com/${{account}}/${{name}}
  summary: jupyterlab-dyno
  description: A jupyter extension to solve .mod DSGE models using dyno.py
  license: BSD-3-Clause
