[workspace]
channels = ["https://repo.prefix.dev/econforge", "conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tasks]
lab = "jupyter lab"
watch = "jlpm watch & jupyter lab"

[dependencies]
jupyterlab = ">=4.0.0,<5"
jupyterlab-dyno = { path = "." }
dyno = { path = "../dyno.py" }
nodejs = ">=24.4.0,<24.5"


[package]
name = "jupyterlab-dyno"
version = "0.1.3"

[package.build]
backend = { name = "pixi-build-python", version = "*" }
build-number = 1

[package.build.config]
noarch = true

[package.host-dependencies] 
hatchling = ">=1.5.0"
hatch-nodejs-version = ">=0.3.2"
hatch-jupyter-builder = ">=0.5.0"
nodejs = ">=24.4.0,<24.5"
jupyterlab = ">=4.0.0,<5"

[package.run-dependencies]
dyno = ">=0.1.12"
xeus-python = ">=0.19"

[feature.video.dependencies]
ffmpeg = "*"

[feature.video.tasks]
video-setup = { cmd = "jlpm install && jlpm playwright install chromium && jupyter labextension develop .. --overwrite", cwd = "ui-tests" }
video = { cmd = "jlpm playwright test -c playwright.videos.config.js", cwd = "ui-tests", depends-on = ["video-setup"] }
video-mp4 = { cmd = "bash videos/to-mp4.sh", cwd = "ui-tests", depends-on = ["video"] }

[environments]
video = ["video"]
